// signalRegistrySnapshot.js
// Mirrors the `signal_definitions` table in Supabase project ajjkcmxytylcrjopxade.
// In production, scoringEngine.js should fetch this from Supabase directly
// (SELECT * FROM signal_definitions WHERE active = true). This static file
// exists so the engine can be developed and tested without a live DB
// connection from this environment, and so the two stay in sync deliberately
// rather than drifting — treat this file as read-only; edit the registry in
// Supabase, then re-export.

const SIGNAL_REGISTRY = [
  { signal_type: 'OWN_ESTATE_TRUST_LLC', category: 'ownership', correlation_group: 'PROBATE_CHAIN', description: 'Estate / Trust / LLC owner', default_base_weight: 7, default_severity: 3, freshness_curve: { default: 1 }, stack_eligible: false, min_confidence_required: 0.5, status: 'CURRENTLY_AVAILABLE', active: true, signal_effect: 'positive' },
  { signal_type: 'OWN_ABSENTEE', category: 'ownership', correlation_group: null, description: 'Absentee owner', default_base_weight: 2, default_severity: 1, freshness_curve: { default: 1 }, stack_eligible: true, min_confidence_required: 0.5, status: 'CURRENTLY_AVAILABLE', active: true, signal_effect: 'positive' },
  { signal_type: 'OWN_OUT_OF_STATE', category: 'ownership', correlation_group: null, description: 'Out-of-state owner', default_base_weight: 2, default_severity: 1, freshness_curve: { default: 1 }, stack_eligible: true, min_confidence_required: 0.5, status: 'CURRENTLY_AVAILABLE', active: true, signal_effect: 'positive' },
  { signal_type: 'OWN_LONG_HOLD', category: 'ownership', correlation_group: null, description: 'Owned 20+ years', default_base_weight: 2, default_severity: 1, freshness_curve: { default: 1 }, stack_eligible: true, min_confidence_required: 0.5, status: 'CURRENTLY_AVAILABLE', active: true, signal_effect: 'positive' },
  { signal_type: 'OWN_FREE_AND_CLEAR', category: 'ownership', correlation_group: null, description: 'Owned free & clear (no mortgage of record)', default_base_weight: 3, default_severity: 2, freshness_curve: { default: 1 }, stack_eligible: true, min_confidence_required: 0.6, status: 'DATA_SOURCE_NEEDED', active: true, signal_effect: 'positive' },
  { signal_type: 'OWN_RECENT_QUITCLAIM', category: 'ownership', correlation_group: 'TITLE_COMPLEXITY', description: 'Quitclaim deed transfer within last 2 years', default_base_weight: 2, default_severity: 2, freshness_curve: { '0-180': 1, '181-365': 0.8, '365+': 0.5 }, stack_eligible: true, min_confidence_required: 0.6, status: 'DATA_SOURCE_NEEDED', active: true, signal_effect: 'positive' },
  { signal_type: 'OWN_MULTIPLE_HEIRS', category: 'ownership', correlation_group: 'PROBATE_CHAIN', description: 'Multiple owners on title (likely heirs)', default_base_weight: 3, default_severity: 2, freshness_curve: { default: 1 }, stack_eligible: true, min_confidence_required: 0.75, status: 'NOT_APPROPRIATE', active: false, signal_effect: 'positive' },
  { signal_type: 'OWN_DECEASED_NO_PROBATE', category: 'ownership', correlation_group: 'PROBATE_CHAIN', description: 'Owner deceased, no probate filed yet', default_base_weight: 5, default_severity: 3, freshness_curve: { '0-180': 1, '181-365': 0.8, '365+': 0.5 }, stack_eligible: false, min_confidence_required: 0.75, status: 'NOT_APPROPRIATE', active: false, signal_effect: 'positive' },

  { signal_type: 'TAX_DELINQUENT', category: 'tax', correlation_group: 'TAX_DISTRESS_CHAIN', description: 'Tax delinquent', default_base_weight: 3, default_severity: 2, freshness_curve: { default: 1 }, stack_eligible: false, min_confidence_required: 0.5, status: 'CURRENTLY_AVAILABLE', active: true, signal_effect: 'positive' },
  { signal_type: 'TAX_MULTI_YEAR', category: 'tax', correlation_group: 'TAX_DISTRESS_CHAIN', description: 'Multiple years of back taxes owed', default_base_weight: 2, default_severity: 2, freshness_curve: { default: 1 }, stack_eligible: false, min_confidence_required: 0.5, status: 'CURRENTLY_AVAILABLE', active: true, signal_effect: 'positive' },
  { signal_type: 'TAX_HIGH_RATIO', category: 'tax', correlation_group: null, description: 'High tax-to-value ratio (>4%)', default_base_weight: 2, default_severity: 1, freshness_curve: { default: 1 }, stack_eligible: true, min_confidence_required: 0.5, status: 'CURRENTLY_AVAILABLE', active: true, signal_effect: 'positive' },
  { signal_type: 'TAX_VERY_LOW_VALUE', category: 'tax', correlation_group: null, description: 'Very low valuation (<$40K, any market)', default_base_weight: 5, default_severity: 3, freshness_curve: { default: 1 }, stack_eligible: true, min_confidence_required: 0.5, status: 'CURRENTLY_AVAILABLE', active: true, signal_effect: 'positive' },
  { signal_type: 'TAX_LOW_DISTRESSED_SUB', category: 'tax', correlation_group: null, description: 'Low value (<$80K) in Gary/Hammond/East Chicago [SUPERSEDED by VAL_LOW_FOR_SUBMARKET]', default_base_weight: 4, default_severity: 2, freshness_curve: { default: 1 }, stack_eligible: true, min_confidence_required: 0.5, status: 'CURRENTLY_AVAILABLE', active: false, signal_effect: 'positive' },
  { signal_type: 'VAL_LOW_FOR_SUBMARKET', category: 'tax', correlation_group: null, description: 'Low valuation relative to submarket norm (tiered)', default_base_weight: 4, default_severity: 2, freshness_curve: { default: 1 }, stack_eligible: true, min_confidence_required: 0.5, status: 'PARTIALLY_AVAILABLE', active: true, signal_effect: 'positive' },
  { signal_type: 'TAX_SALE_SCHEDULED', category: 'tax', correlation_group: 'TAX_DISTRESS_CHAIN', description: 'Tax sale / tax certificate scheduled', default_base_weight: 6, default_severity: 3, freshness_curve: { '0-90': 1, '91-180': 0.7, '181-365': 0.4, '365+': 0.15 }, stack_eligible: false, min_confidence_required: 0.6, status: 'DATA_SOURCE_NEEDED', active: true, signal_effect: 'positive' },
  { signal_type: 'TAX_VALUE_DROPPED_YOY', category: 'tax', correlation_group: null, description: 'Assessed value dropped year-over-year', default_base_weight: 2, default_severity: 1, freshness_curve: { '0-180': 1, '181-365': 0.8, '365+': 0.5 }, stack_eligible: true, min_confidence_required: 0.5, status: 'DATA_SOURCE_NEEDED', active: true, signal_effect: 'positive' },
  { signal_type: 'TAX_HOA_MECHANIC_LIEN', category: 'tax', correlation_group: 'LIEN_STACK', description: "HOA lien or mechanic's lien recorded", default_base_weight: 3, default_severity: 2, freshness_curve: { default: 1 }, stack_eligible: true, min_confidence_required: 0.6, status: 'DATA_SOURCE_NEEDED', active: true, signal_effect: 'positive' },

  { signal_type: 'LEGAL_PRE_FORECLOSURE', category: 'legal', correlation_group: 'FORECLOSURE_CHAIN', description: 'Pre-foreclosure / lis pendens filed', default_base_weight: 6, default_severity: 3, freshness_curve: { '0-90': 1, '91-180': 0.7, '181-365': 0.4, '365+': 0.15 }, stack_eligible: false, min_confidence_required: 0.6, status: 'DATA_SOURCE_NEEDED', active: true, signal_effect: 'positive' },
  { signal_type: 'LEGAL_SHERIFF_SALE_SCHEDULED', category: 'legal', correlation_group: 'FORECLOSURE_CHAIN', description: 'Sheriff sale scheduled', default_base_weight: 7, default_severity: 4, freshness_curve: { '0-90': 1, '91-180': 0.7, '181-365': 0.4, '365+': 0.15 }, stack_eligible: false, min_confidence_required: 0.6, status: 'DATA_SOURCE_NEEDED', active: true, signal_effect: 'positive' },
  { signal_type: 'LEGAL_ZOMBIE_PROPERTY', category: 'legal', correlation_group: 'FORECLOSURE_CHAIN', description: 'Zombie property (foreclosure started, abandoned)', default_base_weight: 5, default_severity: 3, freshness_curve: { '0-180': 1, '181-365': 0.8, '365+': 0.5 }, stack_eligible: false, min_confidence_required: 0.6, status: 'DATA_SOURCE_NEEDED', active: true, signal_effect: 'positive' },
  { signal_type: 'LEGAL_BANKRUPTCY', category: 'legal', correlation_group: null, description: 'Bankruptcy filed', default_base_weight: 4, default_severity: 2, freshness_curve: { '0-90': 1, '91-180': 0.7, '181-365': 0.4, '365+': 0.15 }, stack_eligible: true, min_confidence_required: 0.7, status: 'FUTURE', active: true, signal_effect: 'positive' },
  { signal_type: 'LEGAL_DIVORCE', category: 'legal', correlation_group: 'DIVORCE_CHAIN', description: 'Divorce filing on record', default_base_weight: 4, default_severity: 2, freshness_curve: { '0-90': 1, '91-180': 0.7, '181-365': 0.4, '365+': 0.15 }, stack_eligible: false, min_confidence_required: 0.6, status: 'FUTURE', active: true, signal_effect: 'positive' },
  { signal_type: 'LEGAL_PROBATE', category: 'legal', correlation_group: 'PROBATE_CHAIN', description: 'Probate filed', default_base_weight: 5, default_severity: 3, freshness_curve: { '0-90': 1, '91-180': 0.7, '181-365': 0.4, '365+': 0.15 }, stack_eligible: false, min_confidence_required: 0.6, status: 'FUTURE', active: true, signal_effect: 'positive' },
  { signal_type: 'LEGAL_JUDGMENT', category: 'legal', correlation_group: 'LIEN_STACK', description: 'Judgment or small claims filed against owner', default_base_weight: 3, default_severity: 2, freshness_curve: { default: 1 }, stack_eligible: true, min_confidence_required: 0.6, status: 'FUTURE', active: true, signal_effect: 'positive' },
  { signal_type: 'LEGAL_LANDLORD_EVICTIONS', category: 'legal', correlation_group: 'LANDLORD_DISTRESS_CHAIN', description: 'Landlord with multiple evictions filed', default_base_weight: 3, default_severity: 2, freshness_curve: { '0-90': 1, '91-180': 0.7, '181-365': 0.4, '365+': 0.15 }, stack_eligible: true, min_confidence_required: 0.6, status: 'FUTURE', active: true, signal_effect: 'positive' },

  { signal_type: 'OCC_VACANT', category: 'occupancy', correlation_group: 'VACANCY_CHAIN', description: 'Vacant / unoccupied', default_base_weight: 4, default_severity: 2, freshness_curve: { '0-90': 1, '91-180': 0.7, '181-365': 0.4, '365+': 0.15 }, stack_eligible: false, min_confidence_required: 0.6, status: 'DATA_SOURCE_NEEDED', active: true, signal_effect: 'positive' },
  { signal_type: 'OCC_UTILITY_SHUTOFF', category: 'occupancy', correlation_group: null, description: 'Utility shutoff signal', default_base_weight: 3, default_severity: 2, freshness_curve: { '0-90': 1, '91-180': 0.7, '181-365': 0.4, '365+': 0.15 }, stack_eligible: true, min_confidence_required: 0.75, status: 'NOT_APPROPRIATE', active: false, signal_effect: 'positive' },
  { signal_type: 'OCC_USPS_UNDELIVERABLE', category: 'occupancy', correlation_group: 'VACANCY_CHAIN', description: 'USPS mail returned / undeliverable', default_base_weight: 4, default_severity: 2, freshness_curve: { '0-90': 1, '91-180': 0.7, '181-365': 0.4, '365+': 0.15 }, stack_eligible: false, min_confidence_required: 0.6, status: 'FUTURE', active: true, signal_effect: 'positive' },
  { signal_type: 'OCC_NO_HOMESTEAD', category: 'occupancy', correlation_group: null, description: 'No homestead exemption filed (non-owner-occupied)', default_base_weight: 2, default_severity: 1, freshness_curve: { default: 1 }, stack_eligible: true, min_confidence_required: 0.5, status: 'DATA_SOURCE_NEEDED', active: true, signal_effect: 'positive' },
  { signal_type: 'OCC_SQUATTER_REPORTED', category: 'occupancy', correlation_group: 'VACANCY_CHAIN', description: 'Squatter / unauthorized occupant reported', default_base_weight: 3, default_severity: 2, freshness_curve: { '0-90': 1, '91-180': 0.7, '181-365': 0.4, '365+': 0.15 }, stack_eligible: true, min_confidence_required: 0.6, status: 'DATA_SOURCE_NEEDED', active: true, signal_effect: 'positive' },
  { signal_type: 'OCC_RENTAL_ACTIVE_COMPLAINTS', category: 'occupancy', correlation_group: 'LANDLORD_DISTRESS_CHAIN', description: 'Non-owner-occupied rental with active complaints', default_base_weight: 2, default_severity: 1, freshness_curve: { '0-90': 1, '91-180': 0.7, '181-365': 0.4, '365+': 0.15 }, stack_eligible: true, min_confidence_required: 0.5, status: 'CURRENTLY_AVAILABLE', active: true, signal_effect: 'positive' },
  { signal_type: 'OCC_BOARDED', category: 'occupancy', correlation_group: 'VACANCY_CHAIN', description: 'Boarded windows/doors', default_base_weight: 3, default_severity: 2, freshness_curve: { '0-90': 1, '91-180': 0.7, '181-365': 0.4, '365+': 0.15 }, stack_eligible: true, min_confidence_required: 0.5, status: 'CURRENTLY_AVAILABLE', active: true, signal_effect: 'positive' },
  { signal_type: 'OCC_VACANT_REGISTRATION', category: 'occupancy', correlation_group: 'VACANCY_CHAIN', description: 'Registered as vacant/abandoned property with the city', default_base_weight: 4, default_severity: 2, freshness_curve: { default: 1 }, stack_eligible: false, min_confidence_required: 0.6, status: 'DATA_SOURCE_NEEDED', active: true, signal_effect: 'positive' },

  { signal_type: 'COND_OPEN_VIOLATION', category: 'condition', correlation_group: 'CODE_ENFORCEMENT_CHAIN', description: 'Open code violation', default_base_weight: 3, default_severity: 2, freshness_curve: { '0-90': 1, '91-180': 0.7, '181-365': 0.4, '365+': 0.15 }, stack_eligible: false, min_confidence_required: 0.5, status: 'CURRENTLY_AVAILABLE', active: true, signal_effect: 'positive' },
  { signal_type: 'COND_MULTI_VIOLATION_STACK', category: 'condition', correlation_group: 'CODE_ENFORCEMENT_CHAIN', description: '3+ stacked code violations', default_base_weight: 3, default_severity: 2, freshness_curve: { '0-90': 1, '91-180': 0.7, '181-365': 0.4, '365+': 0.15 }, stack_eligible: false, min_confidence_required: 0.5, status: 'CURRENTLY_AVAILABLE', active: true, signal_effect: 'positive' },
  { signal_type: 'COND_CONDEMNED', category: 'condition', correlation_group: 'CODE_ENFORCEMENT_CHAIN', description: 'Condemned status', default_base_weight: 6, default_severity: 4, freshness_curve: { '0-180': 1, '181-365': 0.8, '365+': 0.5 }, stack_eligible: false, min_confidence_required: 0.5, status: 'CURRENTLY_AVAILABLE', active: true, signal_effect: 'positive' },
  { signal_type: 'COND_NEGLECT', category: 'condition', correlation_group: 'CODE_ENFORCEMENT_CHAIN', description: 'Overgrown / visible neglect', default_base_weight: 2, default_severity: 1, freshness_curve: { '0-90': 1, '91-180': 0.7, '181-365': 0.4, '365+': 0.15 }, stack_eligible: true, min_confidence_required: 0.5, status: 'CURRENTLY_AVAILABLE', active: true, signal_effect: 'positive' },
  { signal_type: 'COND_FIRE_DAMAGE', category: 'condition', correlation_group: null, description: 'Fire damage on record', default_base_weight: 5, default_severity: 3, freshness_curve: { '0-180': 1, '181-365': 0.8, '365+': 0.5 }, stack_eligible: true, min_confidence_required: 0.75, status: 'NOT_APPROPRIATE', active: false, signal_effect: 'positive' },
  { signal_type: 'COND_ROOF_VISIBLE', category: 'condition', correlation_group: null, description: 'Visible roof damage', default_base_weight: 2, default_severity: 1, freshness_curve: { '0-180': 1, '181-365': 0.8, '365+': 0.5 }, stack_eligible: true, min_confidence_required: 0.75, status: 'NOT_APPROPRIATE', active: false, signal_effect: 'positive' },
  { signal_type: 'COND_DAMAGE_REPORT', category: 'condition', correlation_group: null, description: 'Storm / water / structural damage report on file', default_base_weight: 2, default_severity: 1, freshness_curve: { '0-180': 1, '181-365': 0.8, '365+': 0.5 }, stack_eligible: true, min_confidence_required: 0.75, status: 'NOT_APPROPRIATE', active: false, signal_effect: 'positive' },
  { signal_type: 'COND_OLD_NO_PERMITS', category: 'condition', correlation_group: null, description: 'Home 60+ years old with no permit history', default_base_weight: 1, default_severity: 1, freshness_curve: { default: 1 }, stack_eligible: true, min_confidence_required: 0.5, status: 'DATA_SOURCE_NEEDED', active: true, signal_effect: 'positive' },

  { signal_type: 'MKT_STALE_FSBO', category: 'market', correlation_group: 'LISTING_FAILURE_CHAIN', description: 'FSBO listing stale 90+ days', default_base_weight: 3, default_severity: 2, freshness_curve: { '0-90': 1, '91-180': 0.7, '181-365': 0.4, '365+': 0.15 }, stack_eligible: false, min_confidence_required: 0.5, status: 'DATA_SOURCE_NEEDED', active: true, signal_effect: 'positive' },
  { signal_type: 'MKT_FSBO_VACANT_RENTAL', category: 'market', correlation_group: null, description: 'For-rent-by-owner listing sitting vacant', default_base_weight: 2, default_severity: 1, freshness_curve: { '0-90': 1, '91-180': 0.7, '181-365': 0.4, '365+': 0.15 }, stack_eligible: true, min_confidence_required: 0.5, status: 'DATA_SOURCE_NEEDED', active: true, signal_effect: 'positive' },
  { signal_type: 'MKT_PRICE_DROPS', category: 'market', correlation_group: null, description: 'Multiple price reductions', default_base_weight: 2, default_severity: 1, freshness_curve: { '0-90': 1, '91-180': 0.7, '181-365': 0.4, '365+': 0.15 }, stack_eligible: true, min_confidence_required: 0.5, status: 'FUTURE', active: true, signal_effect: 'positive' },
  { signal_type: 'MKT_EXPIRED_MLS', category: 'market', correlation_group: 'LISTING_FAILURE_CHAIN', description: 'Expired MLS listing', default_base_weight: 3, default_severity: 2, freshness_curve: { '0-90': 1, '91-180': 0.7, '181-365': 0.4, '365+': 0.15 }, stack_eligible: false, min_confidence_required: 0.5, status: 'FUTURE', active: true, signal_effect: 'positive' },
  { signal_type: 'MKT_WITHDRAWN_CANCELED_MLS', category: 'market', correlation_group: 'LISTING_FAILURE_CHAIN', description: 'Withdrawn or canceled MLS listing', default_base_weight: 3, default_severity: 2, freshness_curve: { '0-90': 1, '91-180': 0.7, '181-365': 0.4, '365+': 0.15 }, stack_eligible: false, min_confidence_required: 0.5, status: 'FUTURE', active: true, signal_effect: 'positive' },
  { signal_type: 'MKT_RELISTED_NEW_AGENT', category: 'market', correlation_group: 'LISTING_FAILURE_CHAIN', description: 'Relisted with a new agent within 6 months', default_base_weight: 2, default_severity: 1, freshness_curve: { '0-90': 1, '91-180': 0.7, '181-365': 0.4, '365+': 0.15 }, stack_eligible: false, min_confidence_required: 0.5, status: 'FUTURE', active: true, signal_effect: 'positive' },
  { signal_type: 'MKT_BELOW_COMPS_PPSF', category: 'market', correlation_group: null, description: 'Price per sq ft priced below neighborhood comps', default_base_weight: 2, default_severity: 1, freshness_curve: { '0-90': 1, '91-180': 0.7, '181-365': 0.4, '365+': 0.15 }, stack_eligible: true, min_confidence_required: 0.5, status: 'FUTURE', active: true, signal_effect: 'positive' },
  { signal_type: 'MKT_DOM_2X_AVERAGE', category: 'market', correlation_group: null, description: 'Days on market 2x+ the submarket average', default_base_weight: 2, default_severity: 1, freshness_curve: { '0-90': 1, '91-180': 0.7, '181-365': 0.4, '365+': 0.15 }, stack_eligible: true, min_confidence_required: 0.5, status: 'FUTURE', active: true, signal_effect: 'positive' },

  { signal_type: 'LIFE_INHERITED', category: 'lifeEvent', correlation_group: 'PROBATE_CHAIN', description: 'Inherited property signal', default_base_weight: 4, default_severity: 2, freshness_curve: { '0-180': 1, '181-365': 0.8, '365+': 0.5 }, stack_eligible: true, min_confidence_required: 0.6, status: 'FUTURE', active: true, signal_effect: 'positive' },
  { signal_type: 'LIFE_RELOCATION', category: 'lifeEvent', correlation_group: null, description: 'Relocation / job transfer signal', default_base_weight: 2, default_severity: 1, freshness_curve: { default: 1 }, stack_eligible: true, min_confidence_required: 0.75, status: 'NOT_APPROPRIATE', active: false, signal_effect: 'positive' },
  { signal_type: 'LIFE_SENIOR_OWNER', category: 'lifeEvent', correlation_group: null, description: 'Senior owner (70+)', default_base_weight: 2, default_severity: 1, freshness_curve: { default: 1 }, stack_eligible: true, min_confidence_required: 0.75, status: 'NOT_APPROPRIATE', active: false, signal_effect: 'positive' },
  { signal_type: 'LIFE_MILITARY_PCS', category: 'lifeEvent', correlation_group: null, description: 'Active-duty military PCS / deployment signal', default_base_weight: 2, default_severity: 1, freshness_curve: { default: 1 }, stack_eligible: true, min_confidence_required: 0.8, status: 'NOT_APPROPRIATE', active: false, signal_effect: 'positive' },
  { signal_type: 'LIFE_MEDICAL_LIEN', category: 'lifeEvent', correlation_group: 'LIEN_STACK', description: 'Medical lien recorded', default_base_weight: 3, default_severity: 2, freshness_curve: { default: 1 }, stack_eligible: true, min_confidence_required: 0.6, status: 'DATA_SOURCE_NEEDED', active: true, signal_effect: 'positive' },
  { signal_type: 'LIFE_CHILD_SUPPORT_LIEN', category: 'lifeEvent', correlation_group: 'LIEN_STACK', description: 'Child support lien recorded', default_base_weight: 3, default_severity: 2, freshness_curve: { default: 1 }, stack_eligible: true, min_confidence_required: 0.6, status: 'DATA_SOURCE_NEEDED', active: true, signal_effect: 'positive' },
  { signal_type: 'LIFE_FEDERAL_STATE_TAX_LIEN', category: 'lifeEvent', correlation_group: 'LIEN_STACK', description: 'Federal or state tax lien recorded', default_base_weight: 4, default_severity: 2, freshness_curve: { default: 1 }, stack_eligible: true, min_confidence_required: 0.6, status: 'DATA_SOURCE_NEEDED', active: true, signal_effect: 'positive' },
  { signal_type: 'LIFE_JUDGMENT_LIEN', category: 'lifeEvent', correlation_group: 'LIEN_STACK', description: 'Civil judgment lien recorded against owner', default_base_weight: 3, default_severity: 2, freshness_curve: { default: 1 }, stack_eligible: true, min_confidence_required: 0.6, status: 'DATA_SOURCE_NEEDED', active: true, signal_effect: 'positive' },

  { signal_type: 'NBHD_FLOOD_ZONE', category: 'neighborhood', correlation_group: null, description: 'Property in designated flood zone', default_base_weight: 1, default_severity: 1, freshness_curve: { default: 1 }, stack_eligible: true, min_confidence_required: 0.5, status: 'DATA_SOURCE_NEEDED', active: true, signal_effect: 'positive' },
  { signal_type: 'NBHD_ENV_CONTAMINATION', category: 'neighborhood', correlation_group: null, description: 'Environmental contamination site nearby', default_base_weight: 2, default_severity: 1, freshness_curve: { default: 1 }, stack_eligible: true, min_confidence_required: 0.5, status: 'DATA_SOURCE_NEEDED', active: true, signal_effect: 'positive' },
  { signal_type: 'NBHD_VIOLATION_DENSITY', category: 'neighborhood', correlation_group: null, description: 'High code-violation density on this block', default_base_weight: 2, default_severity: 1, freshness_curve: { '0-90': 1, '91-180': 0.7, '181-365': 0.4, '365+': 0.15 }, stack_eligible: true, min_confidence_required: 0.5, status: 'CURRENTLY_AVAILABLE', active: true, signal_effect: 'positive' },
  { signal_type: 'NBHD_SHERIFF_SALE_CLUSTER', category: 'neighborhood', correlation_group: null, description: 'Cluster of nearby sheriff sales', default_base_weight: 2, default_severity: 1, freshness_curve: { '0-90': 1, '91-180': 0.7, '181-365': 0.4, '365+': 0.15 }, stack_eligible: true, min_confidence_required: 0.5, status: 'DATA_SOURCE_NEEDED', active: true, signal_effect: 'positive' },
  { signal_type: 'NBHD_DECLINING_COMPS', category: 'neighborhood', correlation_group: null, description: 'Declining sold comps in submarket', default_base_weight: 2, default_severity: 1, freshness_curve: { '0-180': 1, '181-365': 0.8, '365+': 0.5 }, stack_eligible: true, min_confidence_required: 0.5, status: 'FUTURE', active: true, signal_effect: 'positive' },
  { signal_type: 'NBHD_VACANT_LOT_NEARBY', category: 'neighborhood', correlation_group: null, description: 'Vacant lot or demolished structure nearby', default_base_weight: 1, default_severity: 1, freshness_curve: { default: 1 }, stack_eligible: true, min_confidence_required: 0.5, status: 'DATA_SOURCE_NEEDED', active: true, signal_effect: 'positive' },
  { signal_type: 'NBHD_HIGH_RENTAL_DENSITY', category: 'neighborhood', correlation_group: null, description: 'Block is majority absentee-owned / rental', default_base_weight: 1, default_severity: 1, freshness_curve: { default: 1 }, stack_eligible: true, min_confidence_required: 0.5, status: 'CURRENTLY_AVAILABLE', active: true, signal_effect: 'positive' },
  { signal_type: 'NBHD_RECENT_DISASTER_DECLARATION', category: 'neighborhood', correlation_group: null, description: 'Area under recent FEMA disaster declaration', default_base_weight: 2, default_severity: 1, freshness_curve: { '0-90': 1, '91-180': 0.7, '181-365': 0.4, '365+': 0.15 }, stack_eligible: true, min_confidence_required: 0.5, status: 'DATA_SOURCE_NEEDED', active: true, signal_effect: 'positive' },

  { signal_type: 'DISQ_DO_NOT_CONTACT', category: 'negative', correlation_group: null, description: 'Do-not-contact / opt-out / legal outreach restriction on file', default_base_weight: 0, default_severity: 4, freshness_curve: { default: 1 }, stack_eligible: true, min_confidence_required: 0.9, status: 'CURRENTLY_AVAILABLE', active: true, signal_effect: 'suppress' },
  { signal_type: 'DISQ_RECENT_ARMS_LENGTH_SALE', category: 'negative', correlation_group: null, description: "Recent arm's-length sale on record (not distressed)", default_base_weight: -6, default_severity: 2, freshness_curve: { '0-180': 1, '181-365': 0.6, '365+': 0.2 }, stack_eligible: true, min_confidence_required: 0.6, status: 'DATA_SOURCE_NEEDED', active: true, signal_effect: 'negative' },
  { signal_type: 'DISQ_ACTIVE_MARKET_LISTING', category: 'negative', correlation_group: null, description: 'Active retail listing at or near market price', default_base_weight: -5, default_severity: 2, freshness_curve: { default: 1 }, stack_eligible: true, min_confidence_required: 0.6, status: 'FUTURE', active: true, signal_effect: 'negative' },
  { signal_type: 'DISQ_ALREADY_SOLD', category: 'negative', correlation_group: null, description: 'Property already sold since lead was scraped', default_base_weight: -8, default_severity: 3, freshness_curve: { default: 1 }, stack_eligible: true, min_confidence_required: 0.7, status: 'DATA_SOURCE_NEEDED', active: true, signal_effect: 'negative' },
  { signal_type: 'DISQ_FORECLOSURE_DISMISSED_RECENT', category: 'negative', correlation_group: 'FORECLOSURE_CHAIN', description: 'Foreclosure case dismissed within last 6 months', default_base_weight: -3, default_severity: 1, freshness_curve: { '0-180': 1, '181+': 0.3 }, stack_eligible: true, min_confidence_required: 0.6, status: 'FUTURE', active: true, signal_effect: 'negative' },
];

module.exports = { SIGNAL_REGISTRY };
